config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root "albums#index"
  # devise_for :users, controllers: { sessions: 'users/sessions' }
  get '/my_albums' ,to: 'albums#my_albums'
  get 'tags/:tag', to: 'albums#index', as: :tag

  resources :albums do
    member do
      delete :remove_video 
    end
  end

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/album.rb
class Album < ApplicationRecord
    has_many_attached :videos
    has_one_attached :coverimg
    has_many :taggings
    has_many :tags, through: :taggings
    validates :title, presence: true
    validates :body, presence: true, length: { minimum: 10 }
    def self.tagged_with(name)
      Tag.find_by!(name: name).albums
    end
  
    def self.tag_counts
      Tag.select('tags.*, count(taggings.tag_id) as count').joins(:taggings).group('taggings.tag_id')
    end
  
    def tag_list
      tags.map(&:name).join(', ')
    end
  
    def tag_list=(names)
      self.tags = names.split(',').map do |n|
        Tag.where(name: n.strip).first_or_create!
      end
    end
    def self.ransackable_attributes(auth_object = nil)
      ["body", "created_at", "id", "publisher", "title", "updated_at"]
    end
    def self.ransackable_associations(auth_object = nil)
      ["coverimg_attachment", "coverimg_blob", "videos_attachments", "videos_blobs"]
    end
    ransacker :title_cont do
      Arel::Nodes::SqlLiteral.new("lower(title) like '%#{Ransack::Helpers::Sanitize.sanitize(query).downcase}%'")
    end
    private def album_params
        params.require(:album).permit(:title, :description, :publisher)
    end
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :authenticate_user! , except: [:index, :show]

  def index
    @q = Album.ransack(params[:q])
    @albums = Album.all.where(publisher: true)
  
    if params[:tag].present?
      @albums = @albums.tagged_with(params[:tag]).where(publisher: true)
    else
      @albums = @q.result(distinct: true).where(publisher: true)
    end
  end
  def show
    @album = Album.find(params[:id])
  end
  def new
    @album = Album.new
  end

  def create
    @album = Album.new(album_params)

    if @album.save
      redirect_to @album
    else
      render :new, status: :unprocessable_entity
    end
  end
  def edit
    @album = Album.find(params[:id])
  end

  def update
    @album = Album.find(params[:id])

    if @album.update(album_params)
      redirect_to @album
    else
      render :edit, status: :unprocessable_entity
    end
  end
  def destroy
    @album = Album.find(params[:id])
    @album.destroy

    redirect_to root_path, status: :see_other
  end

  def remove_video
    @album = Album.find(params[:id])
    video_attachment = @album.videos.find(params[:video_id])
    video_attachment.purge 
    redirect_to @album, alert: "Video attachment deleted."
  end

  def my_albums
    # @albums = Album.all
    @q = Album.ransack(params[:q])
    @albums = @q.result(distinct: true).where(publisher: false)
    params[:tag] ? @albums = Album.tagged_with(params[:tag]) : @albums = Album.all.where(publisher: false)
  end
end

private
def album_params
  params.require(:album).permit(:title, :body, :publisher, :coverimg,:tag_list, :tag,:tag_ids,{ tag_ids: [] }, videos: [])
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/views/albums/_form.html.erb
<div class="container d-flex justify-content-center">
  <%= form_with(model: @album, local:true) do |form| %>
    <div>
      <%= form.label :Title %><br>
      <%= form.text_field :title ,class:"formwidth" %>
      <% @album.errors.full_messages_for(:title).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>

    <div>
      <%= form.label :Description %><br>
      <%= form.text_area :body ,class:"formwidth" %>
        <% @album.errors.full_messages_for(:body).each do |message| %>
          <div><%= message %></div>
        <% end %>
    </div>  
    <br>
    <div>
      <%= form.label :Upload_videos %><br>
      <%= form.file_field :videos, multiple: true, direct_upload: true %>
    </div>
    <br>
    <div>
      <%= form.label :upload_a_coverimg %><br>
      <%= form.file_field :coverimg %>
    </div>
    <div class="form-group">
      <%= form.label :publisher %>
      <%= form.check_box :publisher %>
    </div>
    <div class="form-group">
      <%= form.label :tag_ids, 'Tags:' %>
      <%= form.select :tag_ids, options_from_collection_for_select(Tag.order(:name), :id, :name, form.object.tag_ids) %>
    </div>
    <div>
    <br>
      <%= form.submit %>
    </div>
  <% end %>
</div> 
<br> 

app/views/albums/edit.html.erb
<h1 class="text-center">Edit Album</h1>

<%= render "form", album: @album %>

app/views/albums/index.html.erb
<div class="container d-flex justify-content-center">
  <%= search_form_for @q do |form| %>
    <%= form.label :title_cont, "Album Title" %>
    <%= form.search_field :title_cont %>
    <%= form.submit "Search" %>
  <% end %>
</div>
<br>
<div class="bg-light">
  <div class="row row-cols-1 row-cols-md-4 g-4 container-fluid">
    <% @albums.each do |album| %>
      <div class="col">
        <div class="card h-100 img-fluid border border-danger">
          <%if album.coverimg.attached? %>
            <%= image_tag url_for(album.coverimg),style:"height:80%;width:100%" %>
          <% end %>
          <div class="card-body text-center bg-success">
            <b><h5 class="card-title"><%= link_to album.title, album , class:"setcolor"%></h5></b>
            <p class="text-white fs-4"><small>Tags: <%= raw album.tags.map(&:name).map { |t| link_to t, tag_path(t) }.join(', ') %></small></p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <br>
</div>

<div class="container">
  <div class="row bg-light">
    <% @albums.each do |album| %>
      <div class="col-6">
        <p class="text-danger fs-5">Tags:<%= raw album.tags.map(&:name).map { |t| link_to t, tag_path(t) }.join(', ') %></p>
        <p class="btn btn-dark text-white rounded-pill fst-italic"><%= link_to "Read album", album_path(album) %></p>
      </div>
    <% end %>
  </div>
</div>

app/views/albums/my_albums.html.erb
<div class="container d-flex justify-content-center">
  <%= search_form_for @q do |form| %>
    <%= form.label :title_cont, "Album Title" %>
    <%= form.search_field :title_cont %>
    <%= form.submit "Search" %>
  <% end %>
</div>
<h1 class="text-center text-success fst-italic">My Unpublished Albums</h1>

<div class="bg-light">
  <div class="row row-cols-1 row-cols-md-4 g-4 container-fluid">
    <% @albums.each do |album| %>
      <div class="col">
        <div class="card h-100 img-fluid border border-danger">
          <%if album.coverimg.attached? %>
            <%= image_tag url_for(album.coverimg)%>
          <% end %>

          <div class="card-body text-center bg-success">
            <b><h5 class="card-title"><%= link_to album.title, album , class:"setcolor"%></h5></b>
            <p class="text-white fs-4" ><small>Tags: <%= raw album.tags.map(&:name).map { |t| link_to t, tag_path(t) }.join(', ') %></small></p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <br>
</div>

app/views/albums/new.html.erb
<h1 class="text-center">New Album</h1>

<%= render "form", album: @album %>

app/views/albums/show.html.erb
<h1 class="text-success text-center text-uppercase text-decoration-underline lh-lg fst-italic"><%= @album.title %></h1>
<p  class="text-capitalize fs-4 mx-1"><%= @album.body %></p>

<div class="text-center">
  <li style='list-style :none'>
    <% @album.videos.each do |video| %>
      <div class="col d-flex justify-content-center rounded">
        <div class="card h-100 img-fluid border border-dark">
          <video width="320" height="240" controls>
          <source src="<%= url_for(video) %>" type="<%= video.content_type %>">
          </video>
          
          <div class="card-body text-center">
            <b><h5 class="card-title"><button type="button" class="btn btn-link btn-outline-danger rounded-pill text-uppercase mx-2"><%= link_to "Remove video",remove_video_album_path(@album, video_id: video.id), data: {
                        turbo_method: :delete,
                        turbo_confirm: "Are you sure?"
                    }%></button> </h5></b>
          </div>
        </div>
      </div>
      <br>
    <%end %>
  </li>
</div>

<div class="text-center">
  <button type="button" class="btn btn-link btn-outline-warning rounded-pill text-uppercase"><%= link_to "Edit Album", edit_album_path(@album)%></button> 
  <button type="button" class="btn btn-link btn-outline-danger rounded-pill text-uppercase mx-2"><%= link_to "Destroy", album_path(@album), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  }%></button> 
  <br>
  <br>
</div>