config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root "albums#index"
  # devise_for :users, controllers: { sessions: 'users/sessions' }
  get '/my_albums' ,to: 'albums#my_albums'
  get 'tags/:tag', to: 'albums#index', as: :tag

  resources :albums do
    member do
      delete :remove_video 
    end
  end

  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/layouts/_mynav.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-success">
  <div class="container-fluid">
    <a class="navbar-brand " href="<%= root_path %>"><svg xmlns="http://www.w3.org/2000/svg" width="35" height="35" viewBox="0 0 24 24" style="fill: rgba(255,255,255, 1);transform: ;msFilter:;"><path d="M18 7c0-1.103-.897-2-2-2H4c-1.103 0-2 .897-2 2v10c0 1.103.897 2 2 2h12c1.103 0 2-.897 2-2v-3.333L22 17V7l-4 3.333V7z"></path></svg>
          <b class="text-white">Video Albums</b></a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link text-white text-capitalize fs-5 fst-italic" href="<%= root_path %>">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link text-white text-capitalize fs-5 fst-italic" href="<%= new_album_path %>">New Album</a>
        </li>
        <li class="nav-item">
          <%=link_to "My Album", my_albums_path, class:'nav-link text-capitalize text-white fs-5 fst-italic'%>
        </li>
        
        <% if user_signed_in? %>
          <li class="nav-item">
            <%=link_to "edit profile", edit_user_registration_path, class:'nav-link text-capitalize text-white fs-5 fst-italic'%>
          </li>
          <li class="nav-item">
            <%=link_to "logout", destroy_user_session_path, class:'nav-link text-capitalize text-white fs-5 fst-italic', data: 
            { turbo_method: :delete}%>  
          </li>
        <% else %> 
          <li class="nav-item">
            <%=link_to "sign up", new_user_registration_path, class:'nav-link text-capitalize text-white fs-5 fst-italic'%>
          </li>
          <li class="nav-item">
            <%=link_to "Login", new_user_session_path, class:'nav-link text-capitalize text-white fs-5 fst-italic'%>
          </li>
        <% end %>
      </ul>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  </head>

  <body>
    <%= render 'layouts/mynav'%>
     <br>
      <% if user_signed_in? %>
       <span class="text-danger fst-italic fs-5">Logged in as:</span> <strong class="text-success fs-5"><%= current_user.email %></strong>
      <% end %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <p class="notice text-success fs-5"><%= notice %></p>
    <p class="alert text-danger fs-5"><%= alert %></p>
   
    <%= yield %>
  </body>
</html>